#spring:
#  profiles: dev
server:
  port: 8080
person:
  name: zhangsan-dev
  age: 12
  sex: 男
  desc: my name is ${person.name},my age is ${person.age}
my:
  name: houkai_dev
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  number.less.than.ten: ${random.int(10)}
  number.in.range: ${random.int[1024,65536]}